[tool.poetry]
name = "modbot"
version = "0.1.0"
description = ""
license = "AGPL"
readme = "README.md"
authors = ["Luna D Dragon <advaith.madhukar@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
rich = "^11.2.0"
quart = "^0.16.3"
hikari = {extras = ["speedups"], version = "^2.0.0-alpha.106"}
hikari-tanjun = "^2.4.1-alpha.1"
uvloop = "^0.16.0"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
mypy = "^0.931"
flake8 = "^4.0.1"
black = {version = "^22.1.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
